(setq cf-pl-gcc "10")
(setq cf-pl-gcc11 "43")
(setq cf-pl-g++ "1")
(setq cf-pl-g++11 "42")
(setq cf-pl-go "32")
(setq cf-pl-haskel "12")
(setq cf-pl-java-7 "23")
(setq cf-pl-java-8 "36")
(setq cf-pl-fpc "4")
(setq cf-pl-perl "13")
(setq cf-pl-php "6")
(setq cf-pl-python-2 "7")
(setq cf-pl-python-3 "31")
(setq cf-pl-ruby "8")
(setq cf-pl-scala "20")
(setq cf-pl-js "34")

(setq cf-pl-by-ext (make-hash-table :test 'equal))
(puthash ".cpp" cf-pl-g++ cf-pl-by-ext)
(puthash ".cc" cf-pl-g++ cf-pl-by-ext)
(puthash ".c" cf-pl-gcc cf-pl-by-ext)
(puthash ".pas" cf-pl-fpc cf-pl-by-ext)
(puthash ".php" cf-pl-php cf-pl-by-ext)
(puthash ".java" cf-pl-java-7 cf-pl-by-ext)
